using SnapdInvest.Client.Models;
using Refit;

namespace SnapdInvest.Client;

/// <summary>
/// Refit interface mirroring the engine's FastAPI surface.
/// Regenerated by NSwag from the OpenAPI spec once the contract stabilizes.
/// </summary>
public interface IEngineApi
{
    [Get("/v1/health")]
    Task<HealthResponse> GetHealthAsync(CancellationToken ct = default);

    [Get("/v1/portfolio")]
    Task<PortfolioResponse> GetPortfolioAsync(
        [Query] string accountName = "paper",
        CancellationToken ct = default);

    [Get("/v1/audit")]
    Task<List<AuditEventDto>> GetAuditAsync(
        [Query] int limit = 100,
        [AliasAs("event_type")][Query] string? eventType = null,
        CancellationToken ct = default);

    [Post("/v1/run-once")]
    Task<RunOnceResponse> RunOnceAsync(
        [AliasAs("instrument_symbol")][Query] string instrumentSymbol = "AAPL",
        [AliasAs("instrument_exchange")][Query] string instrumentExchange = "NASDAQ",
        CancellationToken ct = default);

    [Post("/v1/agents/run")]
    Task<AgentRunResponse> RunAgentAsync(
        [AliasAs("instrument_symbol")][Query] string instrumentSymbol = "AAPL",
        [AliasAs("instrument_exchange")][Query] string instrumentExchange = "NASDAQ",
        CancellationToken ct = default);

    [Get("/v1/recommendations")]
    Task<List<RecommendationDto>> GetRecommendationsAsync(
        [Query] string? status = null,
        [Query] int limit = 100,
        CancellationToken ct = default);

    [Post("/v1/recommendations/{recId}/approve")]
    Task<ApproveResponse> ApproveRecommendationAsync(
        string recId,
        [Body] ApproveRequest? payload,
        CancellationToken ct = default);

    [Post("/v1/recommendations/{recId}/reject")]
    Task<Dictionary<string, object?>> RejectRecommendationAsync(
        string recId,
        [Body] RejectRequest? payload,
        CancellationToken ct = default);

    [Post("/v1/oauth/saxo/start")]
    Task<AuthorizeUrlResponse> StartSaxoOAuthAsync(
        [AliasAs("account_id")][Query] string accountId,
        CancellationToken ct = default);

    [Get("/v1/oauth/saxo/status")]
    Task<OAuthStatusResponse> GetSaxoOAuthStatusAsync(
        [AliasAs("account_id")][Query] string accountId,
        CancellationToken ct = default);

    [Get("/v1/accounts/{accountId}")]
    Task<AccountInfoResponse> GetAccountAsync(string accountId, CancellationToken ct = default);

    [Post("/v1/accounts")]
    Task<CreateAccountResponse> CreateAccountAsync(
        [Body] CreateAccountRequest payload,
        CancellationToken ct = default);
}
