<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlgoInvest.Client</RootNamespace>
    <AssemblyName>AlgoInvest.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
